spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/document_catalog}
    username: ${DATABASE_USERNAME:document_catalog}
    password: ${DATABASE_PASSWORD:document_catalog}
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    time-zone: UTC
